apply multi-node CI testing with 'goloop'

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -7,10 +7,11 @@ stages:
 
 variables:
   GOLANG_VERSION: "1.12.4"
-  REPO_GO_DEPS: "goloop/go-deps/${CI_COMMIT_REF_NAME}"
+  REPO_GO_DEPS: "goloop/go-deps/${CI_COMMIT_REF_SLUG}"
   PYTHON_VERSION: "3.7.3"
-  REPO_PY_DEPS: "goloop/py-deps/${CI_COMMIT_REF_NAME}"
-  REPO_GOCHAIN: "goloop/gochain/${CI_COMMIT_REF_NAME}"
+  REPO_PY_DEPS: "goloop/py-deps/${CI_COMMIT_REF_SLUG}"
+  REPO_GOCHAIN: "goloop/gochain/${CI_COMMIT_REF_SLUG}"
+  REPO_GOLOOP: "goloop/${CI_COMMIT_REF_SLUG}"
 
 before_script:
   - env
@@ -61,13 +62,13 @@ build:pyee:
   tags:
     - docker
 
-.build:go: &build__go
+build:go:
   image: "${REPO_GO_DEPS}"
   stage: build
-  variables:
-    BUILD_TARGET: all
   script:
-    - make ${BUILD_TARGET}
+    - make gochain
+    - make goloop
+    - make gstool
   artifacts:
     expire_in: 1 day
     paths:
@@ -75,37 +76,24 @@ build:pyee:
   tags:
     - docker
 
-build:gochian:
-  <<: *build__go
-  script:
-    - make gochain
-
-build:goloop:
-  <<: *build__go
-  script:
-    - make goloop
+.pack: &pack
+  image: docker:git
+  stage: pack
+  tags:
+    - docker-build
+  dependencies:
+    - build:pyee
+    - build:go
 
 pack:gochian:
-  image: docker:git
-  stage: pack
+  <<: *pack
   script:
     - sh docker/gochain/build.sh
-  tags:
-    - docker-build
-  dependencies:
-    - build:pyee
-    - build:gochian
 
 pack:goloop:
-  image: docker:git
-  stage: pack
+  <<: *pack
   script:
     - sh docker/goloop/build.sh
-  tags:
-    - docker-build
-  dependencies:
-    - build:pyee
-    - build:goloop
 
 #ITJ : Integration Test Java-sdk
 .integration:java-sdk:gochain: &ITJ__gochain
@@ -115,15 +103,15 @@ pack:goloop:
     - ${REPO_GOCHAIN}
   variables:
     GOCHAIN_CONFIG: "${CI_PROJECT_DIR}/testsuite/data/config.json"
-    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}"
-    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}/gochain.log"
+    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}"
+    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}/gochain.log"
     GOCHAIN_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/env.properties"
   before_script:
     - env
+    - sed -i "s/localhost/$(echo ${REPO_GOCHAIN//\//-}|cut -d ":" -f 1)/" ${GOCHAIN_ENVFILE}
     - cd testsuite
-    - sed -i "s/localhost/$(echo ${REPO_GOCHAIN//\//-}|cut -d ":" -f 1)/" $GOCHAIN_ENVFILE
   script:
-    - ./gradlew test -DNO_SERVER="true" -DCHAIN_ENV="$GOCHAIN_ENVFILE"
+    - ./gradlew test -DNO_SERVER="true" -DCHAIN_ENV="${GOCHAIN_ENVFILE}"
   after_script:
     - cp -r $GOCHAIN_DATA gochain_data
   cache:
@@ -138,8 +126,6 @@ pack:goloop:
       - testsuite/build/reports
   tags:
     - docker
-  dependencies:
-    - pack:gochian
   except:
     - tags
 
@@ -147,30 +133,119 @@ ITJ:gochain:normal:
   <<: *ITJ__gochain
   variables:
     GOCHAIN_CONFIG: "${CI_PROJECT_DIR}/testsuite/data/config.json"
-    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}"
-    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}/gochain.log"
+    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}"
+    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}/gochain.log"
     GOCHAIN_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/env.properties"
   script:
-    - ./gradlew testNormal -DNO_SERVER="true" -DCHAIN_ENV="$GOCHAIN_ENVFILE"
+    - ./gradlew testNormal -DNO_SERVER="true" -DCHAIN_ENV="${GOCHAIN_ENVFILE}"
 
 ITJ:gochain:governance:
   <<: *ITJ__gochain
   variables:
     GOCHAIN_CONFIG: "${CI_PROJECT_DIR}/testsuite/data/govConfig.json"
-    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}"
-    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}/gochain.log"
+    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}"
+    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}/gochain.log"
     GOCHAIN_GENESIS: "${CI_PROJECT_DIR}/testsuite/data/genesisStorage/genesis_normal.json"
     GOCHAIN_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/govEnv.properties"
   script:
-    - ./gradlew testGovernance -DNO_SERVER="true" -DAUDIT="false" -DCHAIN_ENV="$GOCHAIN_ENVFILE"
+    - ./gradlew testGovernance -DNO_SERVER="true" -DAUDIT="false" -DCHAIN_ENV="${GOCHAIN_ENVFILE}"
 
 ITJ:gochain:governance:audit:
   <<: *ITJ__gochain
   variables:
     GOCHAIN_CONFIG: "${CI_PROJECT_DIR}/testsuite/data/govConfig.json"
-    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}"
-    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_JOB_ID}/gochain.log"
+    GOCHAIN_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}"
+    GOCHAIN_LOGFILE: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}/gochain.log"
     GOCHAIN_GENESIS: "${CI_PROJECT_DIR}/testsuite/data/genesisStorage/genesis_audit.json"
     GOCHAIN_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/govEnv.properties"
   script:
-    - ./gradlew testGovernance -DNO_SERVER="true" -DAUDIT="true" -DCHAIN_ENV="$GOCHAIN_ENVFILE"
+    - ./gradlew testGovernance -DNO_SERVER="true" -DAUDIT="true" -DCHAIN_ENV="${GOCHAIN_ENVFILE}"
+
+.integration:java-sdk:goloop: &ITJ__goloop
+  image: docker:java #sh -c 'echo -e "FROM docker:git\nRUN apk add openjdk8" | docker build --tag docker:java -'
+  stage: integration
+  variables:
+    GOLOOP_DOCKER_REPLICAS: 4
+    GOLOOP_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}"
+    GOLOOP_GENESIS: "${CI_PROJECT_DIR}/testsuite/data/genesis.json"
+    GOLOOP_GOD_KEYSTORE: "${CI_PROJECT_DIR}/testsuite/data/keystore_god.json"
+    GOLOOP_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/env.properties"
+  before_script:
+    - env
+    - export SELF_CONTAINER=$(docker ps --filter label=com.gitlab.gitlab-runner.job.id=${CI_JOB_ID} --format {{.ID}});
+      export GOLOOP_DOCKER_MOUNT="/builds/${CI_PROJECT_NAMESPACE}";
+      FORMAT_MOUNT_NAME="{{range .Mounts}}{{if eq .Destination \"/builds/$CI_PROJECT_NAMESPACE\"}}{{.Name}}{{end}}{{end}}";
+      export GOLOOP_DOCKER_VOLUME=$(docker inspect ${SELF_CONTAINER} --format "${FORMAT_MOUNT_NAME}");
+      export GOLOOP_DOCKER_NETWORK=${GOLOOP_DOCKER_NETWORK:-goloop_${CI_JOB_ID}_net};
+      export GOLOOP_DOCKER_PREFIX=${GOLOOP_DOCKER_PREFIX:-goloop-${CI_JOB_ID}};
+      sh docker/goloop/multi.sh create
+    - sh docker/goloop/multi.sh join ${GOLOOP_GENESIS} ${GOLOOP_GOD_KEYSTORE}; cat ${GOLOOP_GENESIS}
+    - sh docker/goloop/multi.sh start
+    - sh docker/goloop/multi.sh env ${GOLOOP_ENVFILE}; cat ${GOLOOP_ENVFILE}
+    - docker network connect --alias test ${GOLOOP_DOCKER_NETWORK} ${SELF_CONTAINER}
+    - cd testsuite
+  script:
+    - ./gradlew testNormal -DNO_SERVER="true" -DCHAIN_ENV="${GOLOOP_ENVFILE}"
+  after_script:
+    - cp -rf $GOLOOP_DATA goloop_data || echo "failed copy $GOLOOP_DATA"
+    - export SELF_CONTAINER=$(docker ps --filter label=com.gitlab.gitlab-runner.job.id=${CI_JOB_ID} --format {{.ID}});
+      export GOLOOP_DOCKER_NETWORK=${GOLOOP_DOCKER_NETWORK:-goloop_${CI_JOB_ID}_net};
+      docker network disconnect ${GOLOOP_DOCKER_NETWORK} ${SELF_CONTAINER}
+    - export GOLOOP_DOCKER_PREFIX=${GOLOOP_DOCKER_PREFIX:-goloop-${CI_JOB_ID}};
+      sh docker/goloop/multi.sh rm
+  cache:
+    key: "$CI_COMMIT_REF_NAME"
+    paths:
+      - testsuite/.gradle
+  artifacts:
+    expire_in: 1 day
+    when: on_failure
+    paths:
+      - goloop_data
+      - testsuite/build/reports
+  tags:
+    - docker-service
+
+ITJ:goloop:normal:
+  <<: *ITJ__goloop
+  variables:
+    GOLOOP_DOCKER_REPLICAS: 4
+    GOLOOP_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}"
+    GOLOOP_GENESIS: "${CI_PROJECT_DIR}/testsuite/data/genesis.json"
+    GOLOOP_GOD_KEYSTORE: "${CI_PROJECT_DIR}/testsuite/data/keystore_god.json"
+    GOLOOP_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/env.properties"
+  script:
+    - ./gradlew testNormal -DNO_SERVER="true" -DCHAIN_ENV="${GOLOOP_ENVFILE}"
+
+ITJ:goloop:governance:
+  <<: *ITJ__goloop
+  variables:
+    GOLOOP_DOCKER_REPLICAS: 4
+    GOLOOP_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}"
+    GOLOOP_GENESIS: "${CI_PROJECT_DIR}/testsuite/data/genesisStorage/genesis_normal.json"
+    GOLOOP_GOD_KEYSTORE: "${CI_PROJECT_DIR}/testsuite/data/keystore_god.json"
+    GOLOOP_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/govEnv.properties"
+  script:
+    - ./gradlew testGovernance -DNO_SERVER="true" -DAUDIT="false" -DCHAIN_ENV="${GOLOOP_ENVFILE}"
+
+ITJ:goloop:governance:audit:
+  <<: *ITJ__goloop
+  variables:
+    GOLOOP_DOCKER_REPLICAS: 4
+    GOLOOP_DATA: "${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID}/${CI_JOB_ID}"
+    GOLOOP_GENESIS: "${CI_PROJECT_DIR}/testsuite/data/genesisStorage/genesis_audit.json"
+    GOLOOP_GOD_KEYSTORE: "${CI_PROJECT_DIR}/testsuite/data/keystore_god.json"
+    GOLOOP_ENVFILE: "${CI_PROJECT_DIR}/testsuite/data/govEnv.properties"
+  script:
+    - ./gradlew testGovernance -DNO_SERVER="true" -DAUDIT="true" -DCHAIN_ENV="${GOLOOP_ENVFILE}"
+
+.cleanup:integration:
+  image: docker:git
+  stage: cleanup
+  script:
+    - export CACHE_DOCKER_CONTAINERS=$(docker container ls -a -f "label=com.gitlab.gitlab-runner.cache.dir=/builds/${CI_PROJECT_NAMESPACE}" --format "{{.ID}}")
+    - for CONTAINER in ${CACHE_DOCKER_CONTAINERS};do
+        docker run --rm --volumes-from ${CONTAINER} alpine rm -rf ${CI_PROJECT_DIR}.tmp/${CI_COMMIT_REF_NAME}/${CI_PIPELINE_ID};
+      done;
+  tags:
+    - docker-service
